using nce.adosql;
using Microsoft.VisualBasic;
using System;
using System.Collections;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Web;
using System.Web.SessionState;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.UI.HtmlControls;
namespace BoatRenting {

  public partial class calendar_i_aspx_cs : System.Web.UI.Page
  {
    public string con = "";
    public Connection oConn = null;
    public const int adEmpty = 0;
    public const int adTinyInt = 16;
    public const int adSmallInt = 2;
    public const int adInteger = 3;
    public const int adBigInt = 20;
    public const int adUnsignedTinyInt = 17;
    public const int adUnsignedSmallInt = 18;
    public const int adUnsignedInt = 19;
    public const int adUnsignedBigInt = 21;
    public const int adSingle = 4;
    public const int adDouble = 5;
    public const int adCurrency = 6;
    public const int adDecimal = 14;
    public const int adNumeric = 131;
    public const int adBoolean = 11;
    public const int adError = 10;
    public const int adUserDefined = 132;
    public const int adVariant = 12;
    public const int adIDispatch = 9;
    public const int adIUnknown = 13;
    public const int adGUID = 72;
    public const int adDate = 7;
    public const int adDBDate = 133;
    public const int adDBTime = 134;
    public const int adDBTimeStamp = 135;
    public const int adBSTR = 8;
    public const int adChar = 129;
    public const int adVarChar = 200;
    public const int adLongVarChar = 201;
    public const int adWChar = 130;
    public const int adVarWChar = 202;
    public const int adLongVarWChar = 203;
    public const int adBinary = 128;
    public const int adVarBinary = 204;
    public const int adLongVarBinary = 205;
    public const int adChapter = 136;
    public const int adFileTime = 64;
    public const int adPropVariant = 138;
    public const int adVarNumeric = 139;
    public const int adArray = 0x2000;
    public const int adCmdStoredProc = 0x0004;
    public const int adParamInput = 0x0001;
    public const int adParamOutput = 0x0002;
    public string boatID = "";
    public string marinaID = "";
    public int nMonth = 0;
    public int nYear = 0;
    public int i = 0;
    //public object nMonthnlastMonth = null;
    public string nMonthnlastMonth = DateTime.Today.Month.ToString();
    public int nlastMonth = 0;
    public int lastDiasMes = 0;
    public int DiasMes = 0;
    public DateTime Fecha;
    public int numday = 0;
    public int lastweek = 0;
    public int IniRestDays = 0;
    public int FinRestDays = 0;
    public DateTime Fecha2;
    public int numday2 = 0;
    public int lastweek2 = 0;
    public int IniRestDays2 = 0;
    public int FinRestDays2 = 0;
    public int contYear = 0;
    public int nDDay = 0;
    public int nMDay = 0;
    public int nYDay = 0;
    public int nM = 0;
    public int nY = 0;
    public DateTime Hoy;
    public int contrest = 0;
    public int cont = 0;
    public int finfirstweek = 0;
    public int inter_week = 0;
    public int num_week = 0;
    public int finweek = 0;
    public int contrest2 = 0;
    public int nNextM = 0;
    public int nNextY = 0;
    public Command cmd = null;
    public Recordset rs = null;
    public string[] ArrDaysStyle = null;
    public Command cmd1 = null;
    public Recordset rs1 = null;
    public string[] ArrHolidayStyle = null;

  }

} 
